/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CalculatorGUI;

/**
 *
 * @author LENOVO
 */
public class CalculatorGUI extends javax.swing.JFrame {

    double firstnum;
    double secondnum;
    double result;
    String operation;
    
    /**
     * Creates new form CalculatorGUI
     */
    public CalculatorGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DisplayInput = new javax.swing.JTextField();
        DisButton1 = new javax.swing.JButton();
        DisButton2 = new javax.swing.JButton();
        DisButton12 = new javax.swing.JButton();
        DisButton3 = new javax.swing.JButton();
        DisButton4 = new javax.swing.JButton();
        DisButton5 = new javax.swing.JButton();
        DisButton13 = new javax.swing.JButton();
        DisButton6 = new javax.swing.JButton();
        DisButton8 = new javax.swing.JButton();
        DisButton0 = new javax.swing.JButton();
        DisButton9 = new javax.swing.JButton();
        DisButton7 = new javax.swing.JButton();
        DisButton11 = new javax.swing.JButton();
        DisButton14 = new javax.swing.JButton();
        DisButton10 = new javax.swing.JButton();
        DisButton15 = new javax.swing.JButton();
        DisButton16 = new javax.swing.JButton();
        DisButton17 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        DisplayInput.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DisplayInput.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        DisButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DisButton1.setText("1");
        DisButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisButton1ActionPerformed(evt);
            }
        });

        DisButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DisButton2.setText("2");
        DisButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisButton2ActionPerformed(evt);
            }
        });

        DisButton12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DisButton12.setText("/");
        DisButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisButton12ActionPerformed(evt);
            }
        });

        DisButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DisButton3.setText("3");
        DisButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisButton3ActionPerformed(evt);
            }
        });

        DisButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DisButton4.setText("4");
        DisButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisButton4ActionPerformed(evt);
            }
        });

        DisButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DisButton5.setText("5");
        DisButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisButton5ActionPerformed(evt);
            }
        });

        DisButton13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DisButton13.setText("*");
        DisButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisButton13ActionPerformed(evt);
            }
        });

        DisButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DisButton6.setText("6");
        DisButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisButton6ActionPerformed(evt);
            }
        });

        DisButton8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DisButton8.setText("8");
        DisButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisButton8ActionPerformed(evt);
            }
        });

        DisButton0.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DisButton0.setText("0");
        DisButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisButton0ActionPerformed(evt);
            }
        });

        DisButton9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DisButton9.setText("9");
        DisButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisButton9ActionPerformed(evt);
            }
        });

        DisButton7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DisButton7.setText("7");
        DisButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisButton7ActionPerformed(evt);
            }
        });

        DisButton11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DisButton11.setText("+/-");
        DisButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisButton11ActionPerformed(evt);
            }
        });

        DisButton14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DisButton14.setText("-");
        DisButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisButton14ActionPerformed(evt);
            }
        });

        DisButton10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DisButton10.setText(".");
        DisButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisButton10ActionPerformed(evt);
            }
        });

        DisButton15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DisButton15.setText("+");
        DisButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisButton15ActionPerformed(evt);
            }
        });

        DisButton16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DisButton16.setText("C");
        DisButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisButton16ActionPerformed(evt);
            }
        });

        DisButton17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DisButton17.setText("=");
        DisButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisButton17ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(DisplayInput, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DisButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DisButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DisButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DisButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DisButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(DisButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(DisButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DisButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(DisButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(DisButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DisButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(DisButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(DisButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DisButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(DisButton16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DisButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DisButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(DisButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(DisplayInput, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DisButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DisButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DisButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DisButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DisButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DisButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DisButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DisButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DisButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DisButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DisButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DisButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DisButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DisButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DisButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DisButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DisButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DisButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DisButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisButton7ActionPerformed
       
        String Enternum = DisplayInput.getText() + DisButton7.getText();
        DisplayInput.setText(Enternum);
        
    }//GEN-LAST:event_DisButton7ActionPerformed

    private void DisButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisButton1ActionPerformed
        
        String Enternum = DisplayInput.getText() + DisButton1.getText();
        DisplayInput.setText(Enternum);
    }//GEN-LAST:event_DisButton1ActionPerformed

    private void DisButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisButton2ActionPerformed
       
        String Enternum = DisplayInput.getText() + DisButton2.getText();
        DisplayInput.setText(Enternum);
        
    }//GEN-LAST:event_DisButton2ActionPerformed

    private void DisButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisButton3ActionPerformed
        
        String Enternum = DisplayInput.getText() + DisButton3.getText();
        DisplayInput.setText(Enternum);
        
    }//GEN-LAST:event_DisButton3ActionPerformed

    private void DisButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisButton4ActionPerformed
       
        String Enternum = DisplayInput.getText() + DisButton4.getText();
        DisplayInput.setText(Enternum);
    }//GEN-LAST:event_DisButton4ActionPerformed

    private void DisButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisButton5ActionPerformed
       
        String Enternum = DisplayInput.getText() + DisButton5.getText();
        DisplayInput.setText(Enternum);
        
    }//GEN-LAST:event_DisButton5ActionPerformed

    private void DisButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisButton6ActionPerformed
        
        String Enternum = DisplayInput.getText() + DisButton6.getText();
        DisplayInput.setText(Enternum);
        
    }//GEN-LAST:event_DisButton6ActionPerformed

    private void DisButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisButton8ActionPerformed
        
        String Enternum = DisplayInput.getText() + DisButton8.getText();
        DisplayInput.setText(Enternum);
        
    }//GEN-LAST:event_DisButton8ActionPerformed

    private void DisButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisButton9ActionPerformed
       
        String Enternum = DisplayInput.getText() + DisButton9.getText();
        DisplayInput.setText(Enternum);
        
    }//GEN-LAST:event_DisButton9ActionPerformed

    private void DisButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisButton16ActionPerformed
        DisplayInput.setText("");
    }//GEN-LAST:event_DisButton16ActionPerformed

    private void DisButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisButton0ActionPerformed
       
        String Enternum = DisplayInput.getText() + DisButton0.getText();
        DisplayInput.setText(Enternum);
    }//GEN-LAST:event_DisButton0ActionPerformed

    private void DisButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisButton15ActionPerformed
       
        firstnum = Double.parseDouble(DisplayInput.getText());
        DisplayInput.setText("");
        operation = "+";
        
    }//GEN-LAST:event_DisButton15ActionPerformed

    private void DisButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisButton14ActionPerformed
      
        firstnum = Double.parseDouble(DisplayInput.getText());
        DisplayInput.setText("");
        operation = "-";
        
    }//GEN-LAST:event_DisButton14ActionPerformed

    private void DisButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisButton13ActionPerformed
        
        firstnum = Double.parseDouble(DisplayInput.getText());
        DisplayInput.setText("");
        operation = "*";
        
    }//GEN-LAST:event_DisButton13ActionPerformed

    private void DisButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisButton12ActionPerformed
       
        firstnum = Double.parseDouble(DisplayInput.getText());
        DisplayInput.setText("");
        operation = "/";
        
    }//GEN-LAST:event_DisButton12ActionPerformed

    private void DisButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisButton10ActionPerformed
       
        String Enternum = DisplayInput.getText() + DisButton10.getText();
        DisplayInput.setText(Enternum);
        
    }//GEN-LAST:event_DisButton10ActionPerformed

    private void DisButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisButton11ActionPerformed
      
        double ops = Double.parseDouble(String.valueOf(DisplayInput.getText()));
        ops = ops * (-1);
        DisplayInput.setText(String.valueOf(ops));
        
    }//GEN-LAST:event_DisButton11ActionPerformed

    private void DisButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisButton17ActionPerformed
       
        String answer;
        secondnum = Double.parseDouble(DisplayInput.getText());
        if(operation == "+")
        {
            result = firstnum + secondnum;
            answer = String.format("%.2f", result);
            DisplayInput.setText(answer);
        }
        
        else if(operation == "-")
        {
            result = firstnum - secondnum;
            answer = String.format("%.2f", result);
            DisplayInput.setText(answer);
        }
        
        else if(operation == "*")
        {
            result = firstnum * secondnum;
            answer = String.format("%.2f", result);
            DisplayInput.setText(answer);
        }
        
        else if(operation == "/")
        {
            result = firstnum / secondnum;
            answer = String.format("%.2f", result);
            DisplayInput.setText(answer);
        }
    }//GEN-LAST:event_DisButton17ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DisButton0;
    private javax.swing.JButton DisButton1;
    private javax.swing.JButton DisButton10;
    private javax.swing.JButton DisButton11;
    private javax.swing.JButton DisButton12;
    private javax.swing.JButton DisButton13;
    private javax.swing.JButton DisButton14;
    private javax.swing.JButton DisButton15;
    private javax.swing.JButton DisButton16;
    private javax.swing.JButton DisButton17;
    private javax.swing.JButton DisButton2;
    private javax.swing.JButton DisButton3;
    private javax.swing.JButton DisButton4;
    private javax.swing.JButton DisButton5;
    private javax.swing.JButton DisButton6;
    private javax.swing.JButton DisButton7;
    private javax.swing.JButton DisButton8;
    private javax.swing.JButton DisButton9;
    private javax.swing.JTextField DisplayInput;
    // End of variables declaration//GEN-END:variables
}
